### ISSUE TITLE
[Pixi] - Le Iene AMP First Site Homepage suffering from CLS on AMP Cache

### ISSUE THREAD

**Issue by gilbertococchi** [ampproject/wg-performance#53]
Hi all, I've noticed on Pixi that this AMP First Site Homepage https://www.iene.mediaset.it/ is suffering from Field CLS 0.16.

<img width="1041" alt="Screenshot 2020-10-21 at 09 31 33" src="https://user-images.githubusercontent.com/329023/96687478-3cb26d00-1380-11eb-9bc6-744cb0fff8fe.png">

By Testing the AMP Cache URL https://www-iene-mediaset-it.cdn.ampproject.org/c/s/www.iene.mediaset.it/ on Chrome DevTools LH Audit it seems like these elements are causing the Layout Shifts:
<img width="712" alt="Screenshot 2020-10-21 at 09 30 28" src="https://user-images.githubusercontent.com/329023/96687375-142a7300-1380-11eb-976d-6897b714500d.png">

Can anybody advice if the issue is happening because of an AMP Core component or guidance on Pixi can be improved on similar outcomes?

/cc @ampproject/wg-performance

**Comment by kevinkimball** [comment]
@gilbertococchi  Hi Gilberto, we ask that you not create issues in this repo directly. The Page Experience tool creates reports automatically when a page has no recommendations and does not meet the CWV standard. In your case I see the tool has some recommendations and suggest you try those. In particular your CLS issue seems to be related to font swapping (try removing the deprecated amp-font component and adding [font-display: swap](https://web.dev/font-display/). If you find a general performance related issue with AMP, please create an issue in the amphtml repo rather than here. Thanks !
