### ISSUE TITLE
timeline poor page experience throught releases?

### ISSUE THREAD

**Issue by barruka** [ampproject/wg-performance#60]
Timeline google search console core web vitals:

I think movements are amp releases related, because we hadn't changed any server side stuff (code, server, hosting, ...) 
Hope this helps to performance team.

Components in use: 

v0
amp-analytics
amp-sidebar
amp-form

Thank you all!

**Comment by kristoferbaxter** [comment]
Can you share a few example URLs impacted?

Do these pages fulfill all the items listed by the AMP Page Experience tool?

**Comment by barruka** [comment]
This report affect to all category pages and product pages: 

Category page:
https://www.irisalia.es/afrodisiacos/perfumes-feromonas

Product page:
https://www.irisalia.es/afrodisiacos/perfumes-feromonas/mai-air-freshener-vanilla

We didn't run the AMP Page Experience tool on each page, but we changed nothing so the only difference are the AMP releases throught the timeline.

**Comment by kristoferbaxter** [comment]
For the category page there are 5 recommendations.
<img width="1093" alt="Screen Shot 2020-11-12 at 7 42 28 AM" src="https://user-images.githubusercontent.com/61764/98961664-ad016980-24ba-11eb-98f3-15f3ad56ef5e.png">

On the product page there are also 5 recommendations.
<img width="1099" alt="Screen Shot 2020-11-12 at 7 44 16 AM" src="https://user-images.githubusercontent.com/61764/98961920-ee921480-24ba-11eb-8166-adf6f0e6aa2b.png">

A few notes to explain these outcomes:
1. CLS impacts are due to not using an AMP Optimizer. AMP Caches, like those at Google will automatically apply a specific optimization removing the AMP boilerplate... doing so on the canonical origin will reduce the CLS issue significantly.

2. Product Page images are oversized and unoptimized. Again, AMP Caches will losslessly optimize the output from the canonical origin... but direct visits will be impacted. Highly recommend using modern formats and optimizing image compression.

Here's an example: https://www.irisalia.es/i/m/MAI-Attraction-Air-Freshener-Vanilla-30-ml-Aromatizador-con-Feromonas.jpg
Original: 213kB
JPG Optimized: 54kB (75% reduction)
WebP Optimized: 40.4kB (81% reduction)
Avif Optimized: 27.4kB (87% reduction)

### Why does this matter?
Visits to AMP documents are a blend of AMP Cache visits and origin visits. To achieve good page performance overall, it's highly recommended to ensure origin pages are optimized to the same degree as cached pages.

There are several factors to CWV, including a changing/expanding audience group that can impact the overall real world performance. Ensuring your documents use all the best recommendations available will give these pages the best opportunities to pass.
